# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 안녕하세요 하이고래의 블로그입니다.
email: kjhihing@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  개발하면서 궁금했던것들을 가볍게 정리하는 블로그 입니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://higore.github.io" # the base hostname & protocol for your site
twitter_username: #안해
github_username:  higore

# Build settings
markdown: kramdown
